    #define GPIO            15
    #define SPI_CS          1    
    #define SPI_MOSI        2
    #define SPI_SCL         3
    #define PWM1            4
    #define PWM2            5
    #define PWM_N_PTC4      6
    #define PWM_P_PTC4      7
    #define PWM_N_PTC3      8
    #define PWM_P_PTC3      9
    #define PWM_N_PTC2      10
    #define PWM_P_PTC2      11
    #define PWM_N_PTC1      12   
    #define PWM_P_PTC1      13
    #define O_UART2_TX      14
	
    #define SPI_MISO            1   
    #define GATE_CLK_PAD_I3     2
    #define GATE_CLK_PAD_I2     3
    #define GATE_CLK_PAD_I 	    4
    #define CAPT_PAD_I4 	    5
    #define CAPT_PAD_I3         6  
    #define CAPT_PAD_I2         7
    #define CAPT_PAD_I          8
    #define EXT_INT3            9
    #define EXT_INT2            10
    #define EXT_INT             11
    #define I_UART2_RX          12