#! /bin/bash -x

#Author : Taimur Islam Khan
#date: 01 Nov, 2022

echo "${1}" > /tmp/debug_filename.txt


openocd -c "set BITFILE ${4}" \
	-f ${3} 
openocd -f ${2} \
	-c "reset halt;load_image ${1}; resume 0x0; exit" 

